# Development Dockerfile for ROS2 with Nvidia GPU support
# Maintainer: Dayuan
version: "1.0"
services:
  ros2_cuda:
    container_name: ros2_foxy_cuda
    image: ros2_cuda_docker
    build: ./
    volumes:
      - ./packages:/root/ws/src/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/:/dev/ # Little bit dangerous, but it works
    working_dir: /root/ws/src/
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"  # Must with this line to enable display
    ipc: host
    privileged: true
    stdin_open: true